apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  labels:
    app: myapp
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: my-image-repo/myapp:latest  # Replace with your image and tag
        ports:
        - containerPort: 8081  # Replace with your application's port
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 256Mi
